# Generated by Django 5.2.8 on 2026-02-04 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the logistics provider', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'carriers',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='PickUpLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_state', models.CharField(max_length=255)),
                ('pickup_city', models.CharField(max_length=255)),
                ('description', models.CharField(help_text='full pickup location description', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Pickup locations',
                'db_table': 'pickup_locations',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'publishers',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('series_type', models.CharField(choices=[('Comic', 'Comic'), ('Manga', 'Manga')], max_length=5)),
                ('image_url', models.CharField(blank=True, max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Series',
                'db_table': 'series',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('phone_no', models.CharField(blank=True, max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authors', models.ManyToManyField(to='src.author')),
                ('genres', models.ManyToManyField(to='src.genre')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='src.series')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('subtotal_amount_usd', models.DecimalField(decimal_places=2, help_text='Total amount of the sku prices', max_digits=10)),
                ('shipping_fee_usd', models.DecimalField(decimal_places=2, help_text='shipping fee cost in usd', max_digits=10)),
                ('total_amount_usd', models.DecimalField(decimal_places=2, help_text='total fee cost', max_digits=10)),
                ('order_exchange_rate', models.DecimalField(decimal_places=2, help_text='Exchange rate from usd to naira during order placement.', max_digits=10)),
                ('shipping_method', models.CharField(choices=[('Local Pickup', 'Pickup'), ('Delivery', 'Delivery')], max_length=13)),
                ('tracking_number', models.CharField(blank=True, max_length=255)),
                ('order_status', models.CharField(blank=True, default='Placed', max_length=255)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='src.carrier')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('pickup_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='src.pickuplocation')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone_no', models.CharField(max_length=255)),
                ('address_state', models.CharField(max_length=255)),
                ('address_city', models.CharField(max_length=255)),
                ('address_street', models.CharField(max_length=300)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='src.order')),
            ],
            options={
                'verbose_name_plural': 'Order Addresses',
                'db_table': 'order_addresses',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('method_type', models.CharField(max_length=255)),
                ('token', models.CharField(blank=True, max_length=255)),
                ('last_four_digits', models.CharField(blank=True, max_length=4)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('provider', models.CharField(max_length=255)),
                ('method_type', models.CharField(max_length=255)),
                ('last_four_digits', models.CharField(blank=True, max_length=4)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(help_text='Currency the customer paid in', max_length=5)),
                ('payment_exchange_rate', models.DecimalField(decimal_places=2, help_text='Exchange rate from usd to naira during payment.', max_digits=10)),
                ('payment_status', models.CharField(default='Pending', max_length=255)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='src.order')),
                ('payment_method_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.paymentmethod')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('isbn_number', models.CharField(help_text='isbn 13 number for the book variant', max_length=255, unique=True)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('format', models.CharField(choices=[('Hardcover', 'Hardcover'), ('Paperback', 'Paperback'), ('Digital', 'Digital')], max_length=9)),
                ('page_count', models.CharField(max_length=255)),
                ('dimensions', models.CharField(blank=True, help_text='Dimensions of hardcover or paperback formats, otherwise empty', max_length=255)),
                ('file_size', models.CharField(blank=True, help_text='Download size of digital format, otherwise empty', max_length=50)),
                ('language', models.CharField(help_text='Language edition of the book', max_length=255)),
                ('published_at', models.DateTimeField()),
                ('is_shipping_free', models.BooleanField(default=False)),
                ('is_discontinued', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='src.book')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='src.publisher')),
            ],
            options={
                'verbose_name_plural': 'Sku',
                'db_table': 'sku',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='src.order')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='src.sku')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.cart')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='src.sku')),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='BookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('view', 'View'), ('add_to_cart', 'Add To Cart'), ('purchase', 'Purchase')], max_length=11)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.book')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.sku')),
            ],
            options={
                'db_table': 'book_events',
            },
        ),
        migrations.CreateModel(
            name='BookAnalyticsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.PositiveBigIntegerField()),
                ('add_to_cart_count', models.PositiveBigIntegerField()),
                ('purchase_count', models.PositiveBigIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.book')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.sku')),
            ],
            options={
                'verbose_name_plural': 'Book Analytics Daily',
                'db_table': 'book_analytics_daily',
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='src.payment', to_field='transaction_id')),
            ],
            options={
                'db_table': 'transaction_logs',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone_no', models.CharField(max_length=255)),
                ('address_state', models.CharField(max_length=255)),
                ('address_city', models.CharField(max_length=255)),
                ('address_street', models.CharField(max_length=300)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': ' User Addresses',
                'db_table': 'user_addresses',
            },
        ),
    ]
