# Generated by Django 5.2.8 on 2026-01-29 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='user_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Deleted', 'Deleted')], default='Active', max_length=9),
        ),
    ]
