# Generated by Django 6.0.3 on 2026-04-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method_id',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
