# Generated by Django 5.2.8 on 2026-01-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_users_created_at_users_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='series_id',
            new_name='series',
        ),
        migrations.RenameField(
            model_name='booksauthorspivot',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='booksauthorspivot',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookspublisherspivot',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookspublisherspivot',
            old_name='publisher_id',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='sku_id',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='carts',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='genrebookspivot',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='genrebookspivot',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='sku_id',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='paymentmethods',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='sku',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='transactionlogs',
            old_name='transaction_id',
            new_name='transaction',
        ),
    ]
