# Generated by Django 5.2.8 on 2026-02-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
