# Generated by Django 6.0.3 on 2026-04-02 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_idempotencykey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='address', to='src.order'),
        ),
    ]
