# Generated by Django 5.2.8 on 2026-02-05 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_series_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='src.series'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sku', to='src.book'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='isbn_number',
            field=models.CharField(help_text='isbn 13 number for the book variant', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='published_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sku',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sku', to='src.publisher'),
        ),
    ]
