# Generated by Django 5.2.8 on 2026-01-30 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_users_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addresses',
            new_name='Address',
        ),
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='BooksAuthorsPivot',
            new_name='BookAuthorPivot',
        ),
        migrations.RenameModel(
            old_name='BooksPublishersPivot',
            new_name='BookPublisherPivot',
        ),
        migrations.RenameModel(
            old_name='Carts',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
        migrations.RenameModel(
            old_name='GenreBooksPivot',
            new_name='GenreBookPivot',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
        migrations.RenameModel(
            old_name='PaymentMethods',
            new_name='PaymentMethod',
        ),
        migrations.RenameModel(
            old_name='Publishers',
            new_name='Publisher',
        ),
        migrations.RenameModel(
            old_name='TransactionLogs',
            new_name='TransactionLog',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.AlterModelOptions(
            name='sku',
            options={'verbose_name_plural': 'Sku'},
        ),
    ]
