# Generated by Django 6.0.3 on 2026-04-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_orderaddress_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_fee_usd',
            new_name='shipping_fee',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='subtotal_amount_usd',
            new_name='subtotal_amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_amount_usd',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_price_usd',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='sku',
            old_name='price_usd',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_shipping_free',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_exchange_rate',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_exchange_rate',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='page_count',
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
