# Generated by Django 5.2.8 on 2026-02-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_book_series_alter_sku_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='series',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='series',
            name='series_type',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default=None, null=True, upload_to='src/images'),
        ),
        migrations.AddField(
            model_name='series',
            name='cover_image',
            field=models.ImageField(default=None, null=True, upload_to='src/images'),
        ),
        migrations.AddField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(related_name='series', to='src.genre'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genres', models.ManyToManyField(related_name='categories', to='src.genre')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'category',
            },
        ),
        migrations.AddField(
            model_name='series',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='series', to='src.category'),
            preserve_default=False,
        ),
    ]
