# Generated by Django 6.0.3 on 2026-04-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_rename_shipping_fee_usd_order_shipping_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
