# Generated by Django 5.2.8 on 2026-01-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_rename_addresses_address_rename_authors_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
