# Generated by Django 5.2.8 on 2026-02-06 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_remove_book_genres_remove_book_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='series', to='src.category'),
        ),
    ]
