# Generated by Django 5.2.8 on 2026-02-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_series_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='src/images'),
        ),
        migrations.AlterField(
            model_name='series',
            name='cover_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='src/images'),
        ),
    ]
