# Generated by Django 6.0.3 on 2026-04-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_sku_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, default='Pending', max_length=255),
        ),
    ]
