# Generated by Django 5.2.8 on 2026-01-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_user_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
