# Generated by Django 6.0.3 on 2026-04-11 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='transaction',
        ),
        migrations.RenameField(
            model_name='transactionlog',
            old_name='events',
            new_name='event',
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='src.order'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
