# Generated by Django 5.2.8 on 2026-01-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='series_type',
            field=models.CharField(choices=[('Comic', 'Comic'), ('Manga', 'Manga')], default='Manga', max_length=5),
        ),
    ]
