# Generated by Django 5.2.8 on 2026-02-09 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_alter_book_cover_image_alter_series_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='sku',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
