# Generated by Django 5.2.8 on 2026-02-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_sku_discount_percent_alter_sku_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookanalyticsdaily',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='bookevent',
            old_name='date',
            new_name='created_at',
        ),
    ]
