# Generated by Django 5.2.8 on 2026-01-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_series_series_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='series_type',
            field=models.CharField(choices=[('Comic', 'Comic'), ('Manga', 'Manga')], max_length=5),
        ),
    ]
