# Generated by Django 5.2.8 on 2026-02-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_rename_date_bookanalyticsdaily_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookanalyticsdaily',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookevent',
            name='book',
        ),
    ]
