# Generated by Django 6.0.3 on 2026-04-14 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nigerian_states', '0001_initial'),
        ('src', '0009_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nigerian_states.localgovernment'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nigerian_states.state'),
        ),
    ]
