# Generated by Django 6.0.3 on 2026-04-14 15:19

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nigerian_states', '0001_initial'),
        ('src', '0009_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='address_state', chained_model_field='state', on_delete=django.db.models.deletion.RESTRICT, to='nigerian_states.localgovernment'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nigerian_states.state'),
        ),
    ]
