# Generated by Django 5.2.8 on 2026-02-01 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_alter_series_series_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BookAnalyticsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.PositiveBigIntegerField()),
                ('add_to_cart_count', models.PositiveBigIntegerField()),
                ('purchase_count', models.PositiveBigIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.book')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.sku')),
            ],
            options={
                'verbose_name_plural': 'Book Analytics Daily',
                'db_table': 'book_analytics_daily',
            },
        ),
        migrations.CreateModel(
            name='BookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=11)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.book')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.sku')),
            ],
            options={
                'db_table': 'book_events',
            },
        ),
    ]
