# Generated by Django 5.2.8 on 2026-02-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_remove_bookanalyticsdaily_book_remove_bookevent_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='bookanalyticsdaily',
            name='created_at',
            field=models.DateField(help_text='indicates the date/day the analytics is collected for, not the date this row is created.'),
        ),
        migrations.AlterField(
            model_name='bookevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='cover_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='covers'),
        ),
        migrations.AlterUniqueTogether(
            name='bookanalyticsdaily',
            unique_together={('sku', 'created_at')},
        ),
        migrations.AddIndex(
            model_name='bookanalyticsdaily',
            index=models.Index(fields=['created_at', 'sku'], name='book_analyt_created_1cf8dd_idx'),
        ),
    ]
