# Generated by Django 5.2.8 on 2026-02-10 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_alter_book_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookanalyticsdaily',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_analytics', to='src.sku'),
        ),
    ]
