# Generated by Django 5.2.8 on 2026-02-11 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_alter_bookanalyticsdaily_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='is_shipping_free',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='language',
        ),
        migrations.AddField(
            model_name='book',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='book',
            name='bestseller_score',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='is_shipping_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='reviewer_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='trending_score',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='src.book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings',
                'unique_together': {('book', 'user')},
            },
        ),
    ]
