# Generated by Django 5.2.8 on 2026-02-12 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_remove_sku_is_shipping_free_remove_sku_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookanalyticsdaily',
            name='book',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_analytics', to='src.book'),
        ),
        migrations.AlterField(
            model_name='bookanalyticsdaily',
            name='add_to_cart_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bookanalyticsdaily',
            name='purchase_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bookanalyticsdaily',
            name='view_count',
            field=models.PositiveIntegerField(),
        ),
    ]
