# Generated by Django 5.2.8 on 2026-02-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_bookanalyticsdaily_book_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
        migrations.AlterField(
            model_name='sku',
            name='format',
            field=models.CharField(choices=[('hardcover', 'Hardcover'), ('paperback', 'Paperback'), ('digital', 'Digital')], max_length=9),
        ),
    ]
