# Generated by Django 5.2.8 on 2026-02-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_rename_ratings_rating_alter_sku_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='format',
            field=models.CharField(choices=[('Hardcover', 'Hardcover'), ('Paperback', 'Paperback'), ('Digital', 'Digital')], max_length=9),
        ),
    ]
