# Generated by Django 5.2.8 on 2026-02-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0019_cartitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
