# Generated by Django 6.0.2 on 2026-03-02 18:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0020_alter_cartitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='public_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='public_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
