# Generated by Django 6.0.2 on 2026-03-11 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0022_alter_series_public_id_alter_sku_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='public_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
