# Generated by Django 6.0.2 on 2026-03-11 16:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0024_alter_cart_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='public_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
