# Generated by Django 6.0.2 on 2026-03-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0025_alter_cart_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_location',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tracking_number',
            new_name='tracking_id',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='address_street',
            new_name='address_desc',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='recipient_name',
            new_name='recipient_firstname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_method',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='recipient_lastname',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Carrier',
        ),
        migrations.DeleteModel(
            name='PickUpLocation',
        ),
    ]
