# Generated by Django 6.0.3 on 2026-04-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0025_alter_cart_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='address_street',
            new_name='address_desc',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='recipient_name',
            new_name='recipient_firstname',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='recipient_lastname',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
