# Generated by Django 6.0.2 on 2026-03-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0026_remove_order_carrier_remove_order_pickup_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
