# Generated by Django 6.0.2 on 2026-03-26 03:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0027_alter_order_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
