# Generated by Django 6.0.2 on 2026-03-26 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0028_alter_order_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price_usd',
        ),
    ]
