# Generated by Django 6.0.2 on 2026-03-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0029_remove_orderitem_total_price_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderaddress',
            old_name='address_street',
            new_name='address_desc',
        ),
        migrations.RenameField(
            model_name='orderaddress',
            old_name='recipient_name',
            new_name='recipient_firstname',
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='recipient_email',
            field=models.EmailField(default=None, max_length=255, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='recipient_lastname',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
