# Generated by Django 6.0.2 on 2026-03-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0030_rename_address_street_orderaddress_address_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, default='Pending', max_length=255),
        ),
    ]
