# Generated by Django 6.0.2 on 2026-03-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0031_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='recipient_email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
    ]
